network/urls.py
from django.conf import settings
from django.urls import include, path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("following", views.following, name="following"),
    path("post-message", views.postmessage, name="postmessage"),
    path("like/<int:id>", views.like, name="like"),
    path("profile/<str:username>", views.profile, name="profile"),
    path("follow/<int:id>", views.follow, name="follow"),
    path("editpost/<int:id>", views.editpost, name="editpost")

]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime


class User(AbstractUser):
    pass


class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=160, default=None)
    post_date = models.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        return f"{self.user} to {self.text}"


class Follower(models.Model):
    follower = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='follower', default=None)
    following = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='following', default=None)

    class Meta:
        unique_together = (('follower', 'following'),)
    def __str__(self):
            return f"{self.follower} : {self.following}"


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    class Meta:
        unique_together = (('post', 'user'),)

    def __str__(self):
        return f"{self.post} : {self.user}"

network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.urls import reverse
from network.models import User, Post, Follower, Like
from django import forms
from django.db.models import OuterRef, Subquery, Count, Exists
from django.views.generic import ListView
from django.core.paginator import Paginator
import time

MAX_POSTS_PER_PAGE = 10


class NewPostForm(forms.Form):
    """The new form class
    """
    post_text = forms.Field(widget=forms.Textarea(
        {'rows': '3', 'maxlength': 160, 'class': 'form-control', 'placeholder': "What's happening?"}), label="New Post", required=True)


class NewEditPostForm(forms.Form):
    """The edit post form class
    """
    id_post_edit_text = forms.Field(widget=forms.Textarea(
        {'rows': '3', 'maxlength': 160, 'class': 'form-control', 'placeholder': "What's happening?", 'id': 'id_post_edit_text'}), label="New Post", required=True)


def index(request):

    if request.user.is_authenticated:
        user = request.session['_auth_user_id']
        likes = Like.objects.filter(post=OuterRef('id'), user_id=user)
        posts = Post.objects.filter().order_by(
            '-post_date').annotate(current_like=Count(likes.values('id')))
    else:
        posts = Post.objects.order_by('-post_date').all()

    paginator = Paginator(posts, MAX_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "network/index.html", {
        'posts': page_obj,
        'form': NewPostForm(),
        'form_edit': NewEditPostForm()
    })


def following(request):
    if request.user.is_authenticated:
        user = request.session['_auth_user_id']
        followers = Follower.objects.filter(follower=user)
        likes = Like.objects.filter(post=OuterRef('id'), user_id=user)
        posts = Post.objects.filter(user_id__in=followers.values('following_id')).order_by(
            '-post_date').annotate(current_like=Count(likes.values('id')))
    else:
        return HttpResponseRedirect(reverse("login"))

    paginator = Paginator(posts, MAX_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "network/following.html", {
        'posts': page_obj,
        'form': NewPostForm()
    })


def postmessage(request):

    if request.method == "POST":
        form = NewPostForm(request.POST)
        if form.is_valid():
            user = User.objects.get(id=request.session['_auth_user_id'])
            text = form.cleaned_data["post_text"]
            post = Post(user=user, text=text)
            post.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        return HttpResponseRedirect(reverse("index"))


def editpost(request, id):
    if request.is_ajax and request.method == "POST":
        form = NewEditPostForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data["id_post_edit_text"]
            Post.objects.filter(
                id=id, user_id=request.session['_auth_user_id']).update(text=text)
            return JsonResponse({"result": 'ok', 'text': text})
        else:
            return JsonResponse({"error": form.errors}, status=400)

    return JsonResponse({"error": HttpResponseBadRequest("Bad Request: no like chosen")}, status=400)


def follow(request, id):
    try:
        result = 'follow'
        user = User.objects.get(id=request.session['_auth_user_id'])
        user_follower = User.objects.get(id=id)
        follower = Follower.objects.get_or_create(
            follower=user, following=user_follower)
        if not follower[1]:
            Follower.objects.filter(
                follower=user, following=user_follower).delete()
            result = 'unfollow'
        total_followers = Follower.objects.filter(
            following=user_follower).count()
    except KeyError:
        return HttpResponseBadRequest("Bad Request: no like chosen")
    return JsonResponse({"result": result, "total_followers": total_followers})


def like(request, id):

    try:
        css_class = 'fas fa-heart'
        user = User.objects.get(id=request.session['_auth_user_id'])
        post = Post.objects.get(id=id)
        like = Like.objects.get_or_create(
            user=user, post=post)
        if not like[1]:
            css_class = 'far fa-heart'
            Like.objects.filter(user=user, post=post).delete()

        total_likes = Like.objects.filter(post=post).count()
    except KeyError:
        return HttpResponseBadRequest("Bad Request: no like chosen")
    return JsonResponse({
        "like": id, "css_class": css_class, "total_likes": total_likes
    })


def profile(request, username):
    is_following=0
    profile_user = User.objects.get(username=username)
    if request.user.is_authenticated:
        logged_user = request.session['_auth_user_id']
        is_following = Follower.objects.filter(
        follower=logged_user, following=profile_user).count()
        likes = Like.objects.filter(post=OuterRef('id'), user_id=logged_user)
        posts = Post.objects.filter(user=profile_user).order_by(
            'post_date').annotate(current_like=Count(likes.values('id')))
    else:
        posts = Post.objects.filter(
            user=profile_user).order_by('post_date').all()

    
    total_following = Follower.objects.filter(
        follower=profile_user).count()
    total_followers = Follower.objects.filter(
        following=profile_user).count()

    paginator = Paginator(posts, MAX_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "network/profile.html", {
        "user_profile": profile_user, "posts": page_obj, "is_following": is_following, 'total_following': total_following, 'total_followers': total_followers, 'form': NewPostForm(), 'form_edit': NewEditPostForm()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")

network/templates/network/following.html
{% extends "network/layout.html" %}

{% block body %}
<h1>Following</h1>
<div id="posts">
    {% for post in posts %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'profile' post.user.username %}">{{post.user.username}}</a></h5>
            {%if post.user_id == user.id %}
            <a href="#" class="card-link" id="edit_link_{{post.id}}" data-id="{{post.id}}" data-toggle="modal">Edit</a>
            {%endif%}
            <p class="card-text" id="post_text_{{post.id}}"> {{ post.text }}</p>
            <form action="#" method="POST" id="frm_edit_{{post.id}}" data-id="{{post.id}}" style="display: none">
                {% csrf_token %}
                <div class="form-group">
                    {{ form_edit.id_post_edit_text }}
                </div>
                <div id="post_text_alert_{{post.id}}">
                </div>
                <button type="button" data-id="{{post.id}}" id="btn_close_{{post.id}}" class="btn btn-secondary"
                    data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="btnSave">Save changes</button>
            </form>

            <p class="card-text"><small class="text-muted">{{post.post_date}}</small></p>
            <p class="card-text">
                <div data-id="{{post.id}}"
                    class="card-link {% if post.current_like > 0 %} fas {%else%} far {% endif %} fa-heart">&nbsp<small
                        class="text-muted">{{post.like_set.count}}</small></div>
            </p>
        </div>
    </div>
    {% empty %}
    <h2>No posts</h2>
    {% endfor %}
</div>
{% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
<h1>All Posts</h1>
 {% include "network/post_form.html" %}
<div id="posts">
    {% for post in posts %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'profile' post.user.username %}">{{post.user.username}}</a></h5>
            {%if post.user_id == user.id %}
            <a href="#" class="card-link" id="edit_link_{{post.id}}" data-id="{{post.id}}" data-toggle="modal">Edit</a>
            {%endif%}
            <p class="card-text" id="post_text_{{post.id}}"> {{ post.text }}</p>
            <form action="#" method="POST" id="frm_edit_{{post.id}}" data-id="{{post.id}}" style="display: none">
                {% csrf_token %}
                <div class="form-group">
                    {{ form_edit.id_post_edit_text }}
                </div>
                <div id="post_text_alert_{{post.id}}">
                </div>
                <div id="div_buttons">
                <button type="button" data-id="{{post.id}}" id="btn_close_{{post.id}}" class="btn btn-secondary"
                    data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="btnSave">Save changes</button>
                </div>
            </form>

            <p class="card-text"><small class="text-muted">{{post.post_date}}</small></p>
            <p class="card-text">
                <div data-id="{{post.id}}"
                    class="card-link {% if post.current_like > 0 %} fas {%else%} far {% endif %} fa-heart">&nbsp<small
                        class="text-muted">{{post.like_set.count}}</small>
                        </div>
            </p>
        </div>
    </div>
    {% empty %}
    <h2>No posts</h2>
    {% endfor %}
</div>


{% endblock %}

network/templates/network/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Social Network{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
    <link href="{% static 'network/styles.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Network</a>
        <div>
            {% with request.resolver_match.url_name as url_name %}
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item {% if url_name == 'profile' %}active{% endif %}">
                    <a class="nav-link"
                        href="{% url 'profile' user.username %}"><strong>{{ user.username }}</strong></a>
                </li>
                {% endif %}
                <li class="nav-item {% if url_name == 'index' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item {% if url_name == 'following' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'following' %}">Following</a>
                </li>
                <li class="nav-item {% if url_name == 'logout' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item {% if url_name == 'login' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item {% if url_name == 'register' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
            {% endwith %}
        </div>
    </nav>
    <div class="body">
        {% block body %}
        {% endblock %}
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">
                    Previous
                </a>
            </li>
            {% endif %}
            {%if posts.paginator.num_pages > 1 %}
            {% for num in posts.paginator.page_range %}
            {% if posts.number == num %}
            <li class="page-item active">
                <a class="page-link">{{ num }}</a>
            </li>
            {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">
                    Next
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{% static 'network/library.js' %}"></script>

</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

network/templates/network/post_form.html
{% if user.is_authenticated %}
<div class="card">
    <div class="card-body">
        <form action="{% url 'postmessage' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="post_text" class="h4">New Post</label>
                {{ form.post_text }}
            </div>
            <button type="submit" class="btn btn-primary btn-sm">Post</button>
        </form>
    </div>
</div>
{%endif%}

network/templates/network/profile.html
{% extends "network/layout.html" %}

{% block body %}
<div class="card">
    <div class="card-body">
        <h1 class="card-title">{{user_profile.username}}</h1>
        <h5 class="card-text"><span id="sp_following">{{total_following}}</span> Following</h5>
        <h5 class="card-text"><span id="sp_followers">{{total_followers}}</span> Followers</h5>
        <p class="card-text"><small class="text-muted"></small></p>
        {% if user.is_authenticated and user.id != user_profile.id %}
        <p class="card-text">
        {% if is_following > 0 %}
            <button id="btnfollow" data-id="{{user_profile.id}}" type="button" class="btn btn-primary">Following</button>
        {% else %}
            <button id="btnfollow" data-id="{{user_profile.id}}" type="button" class="btn btn-outline-primary">Follow</button>
        {%endif%}
        </p>
        {%endif%}
    </div>
</div>
<div id="content">
    <h3>All Posts</h3>
    {% for post in posts %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'profile' post.user.username %}">{{post.user.username}}</a></h5>
            {%if post.user_id == user.id %}
            <a href="#" class="card-link" id="edit_link_{{post.id}}" data-id="{{post.id}}" data-toggle="modal">Edit</a>
            {%endif%}
            <p class="card-text" id="post_text_{{post.id}}"> {{ post.text }}</p>
            <form action="#" method="POST" id="frm_edit_{{post.id}}" data-id="{{post.id}}" style="display: none">
                {% csrf_token %}
                <div class="form-group">
                    {{ form_edit.id_post_edit_text }}
                </div>
                <div id="post_text_alert_{{post.id}}">
                </div>
                <div id="div_buttons">
                <button type="button" data-id="{{post.id}}" id="btn_close_{{post.id}}" class="btn btn-secondary"
                    data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="btnSave">Save changes</button>
                </div>
            </form>

            <p class="card-text"><small class="text-muted">{{post.post_date}}</small></p>
            <p class="card-text">
                <div data-id="{{post.id}}"
                    class="card-link {% if post.current_like > 0 %} fas {%else%} far {% endif %} fa-heart">&nbsp<small
                        class="text-muted">{{post.like_set.count}}</small>
                        </div>
            </p>
        </div>
    </div>
    {% empty %}
    <h2>No posts</h2>
    {% endfor %}
</div>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}